name: Tests and Formatting
on:
    push:
        branches:
          - '*'
    pull_request:
        branches: [main]
jobs:
    run_unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.0
            - run:
                cd test/unit
                python3 -m unittest test_my_utils.py
                cd ../..
    run_style_tests:
        runs-on: ubuntu-latest
        steps:
            -uses: actions/checkout@v3.0
            -run: pycodestyle $(git ls-files "*.py")
    run_func_tests:
        runs-on: ubuntu-latest
        steps:
            -uses: actions/checkout@v3.0
            - run: 
            bash test_my_utils_functional.sh
